name: build-phar

on:
  push:
    branches:
      - master

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M, phar.readonly=0
          tools: composer:v2
          coverage: none
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          architecture: x64
          check-latest: true
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ~/.npm
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
      - name: Install dependencies
        run: |
          composer install --ignore-platform-reqs
          npm install -g html-minifier terser
      - name: Build phar archive
        run: |
          wget https://git.io/JtDYf -O phar-builder.php
          php phar-builder.php build-phar.json
          html-minifier --collapse-whitespace --collapse-boolean-attributes --decode-entities --remove-comments --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --remove-empty-attributes --use-short-doctype --process-conditional-comments --sort-attributes --sort-class-name --minify-css true --minify-js true --putput public/index.html public/index.html
          terser --ecma 2020 --compress unsafe_math,unsafe_methods,unsafe_proto,unsafe_regexp,unsafe_undefined --mangle --comments false --output public/app.js public/app.js
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: IBSjnuweb
          path: |
            IBSjnuweb.phar
            index.php
            public/app.js
            public/index.html
        if: ${{ always() }}